version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - default
      - easypanel
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.barbersaas.rule=Host(`controlbarber.online`)"
      - "traefik.http.services.barbersaas.loadbalancer.server.port=80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped
    env_file:
      - ./backend/.env

networks:
  easypanel:
    external: true
